package ai

// Code generated by go run ./cmd/modelcataloggen. DO NOT EDIT.
// Source: https://models.dev/api.json
// Provider scope in this port: kimi-coding, openai, openai-codex, zai.
//
//go:generate go run ../../cmd/modelcataloggen -out models_generated.go
var generatedModelsJSON = `
{
  "kimi-coding": {
    "k2p5": {
      "id": "k2p5",
      "name": "Kimi K2.5",
      "api": "anthropic-messages",
      "provider": "kimi-coding",
      "baseUrl": "https://api.kimi.com/coding/v1",
      "reasoning": true,
      "input": [
        "text",
        "image",
        "video"
      ],
      "cost": {
        "input": 0,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 262144,
      "maxTokens": 32768
    },
    "kimi-k2-thinking": {
      "id": "kimi-k2-thinking",
      "name": "Kimi K2 Thinking",
      "api": "anthropic-messages",
      "provider": "kimi-coding",
      "baseUrl": "https://api.kimi.com/coding/v1",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 262144,
      "maxTokens": 32768
    }
  },
  "openai": {
    "codex-mini-latest": {
      "id": "codex-mini-latest",
      "name": "Codex Mini",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 1.5,
        "output": 6,
        "cacheRead": 0.375,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "gpt-3.5-turbo": {
      "id": "gpt-3.5-turbo",
      "name": "GPT-3.5-turbo",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0.5,
        "output": 1.5,
        "cacheRead": 1.25,
        "cacheWrite": 0
      },
      "contextWindow": 16385,
      "maxTokens": 4096
    },
    "gpt-4": {
      "id": "gpt-4",
      "name": "GPT-4",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text"
      ],
      "cost": {
        "input": 30,
        "output": 60,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 8192,
      "maxTokens": 8192
    },
    "gpt-4-turbo": {
      "id": "gpt-4-turbo",
      "name": "GPT-4 Turbo",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 10,
        "output": 30,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 4096
    },
    "gpt-4.1": {
      "id": "gpt-4.1",
      "name": "GPT-4.1",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 2,
        "output": 8,
        "cacheRead": 0.5,
        "cacheWrite": 0
      },
      "contextWindow": 1047576,
      "maxTokens": 32768
    },
    "gpt-4.1-mini": {
      "id": "gpt-4.1-mini",
      "name": "GPT-4.1 mini",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 0.4,
        "output": 1.6,
        "cacheRead": 0.1,
        "cacheWrite": 0
      },
      "contextWindow": 1047576,
      "maxTokens": 32768
    },
    "gpt-4.1-nano": {
      "id": "gpt-4.1-nano",
      "name": "GPT-4.1 nano",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 0.1,
        "output": 0.4,
        "cacheRead": 0.03,
        "cacheWrite": 0
      },
      "contextWindow": 1047576,
      "maxTokens": 32768
    },
    "gpt-4o": {
      "id": "gpt-4o",
      "name": "GPT-4o",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 2.5,
        "output": 10,
        "cacheRead": 1.25,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 16384
    },
    "gpt-4o-2024-05-13": {
      "id": "gpt-4o-2024-05-13",
      "name": "GPT-4o (2024-05-13)",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 5,
        "output": 15,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 4096
    },
    "gpt-4o-2024-08-06": {
      "id": "gpt-4o-2024-08-06",
      "name": "GPT-4o (2024-08-06)",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 2.5,
        "output": 10,
        "cacheRead": 1.25,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 16384
    },
    "gpt-4o-2024-11-20": {
      "id": "gpt-4o-2024-11-20",
      "name": "GPT-4o (2024-11-20)",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 2.5,
        "output": 10,
        "cacheRead": 1.25,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 16384
    },
    "gpt-4o-mini": {
      "id": "gpt-4o-mini",
      "name": "GPT-4o mini",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 0.15,
        "output": 0.6,
        "cacheRead": 0.08,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 16384
    },
    "gpt-5": {
      "id": "gpt-5",
      "name": "GPT-5",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0.125,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5-chat-latest": {
      "id": "gpt-5-chat-latest",
      "name": "GPT-5 Chat (latest)",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5-codex": {
      "id": "gpt-5-codex",
      "name": "GPT-5-Codex",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0.125,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5-mini": {
      "id": "gpt-5-mini",
      "name": "GPT-5 Mini",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 0.25,
        "output": 2,
        "cacheRead": 0.025,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5-nano": {
      "id": "gpt-5-nano",
      "name": "GPT-5 Nano",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 0.05,
        "output": 0.4,
        "cacheRead": 0.005,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5-pro": {
      "id": "gpt-5-pro",
      "name": "GPT-5 Pro",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 15,
        "output": 120,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 272000
    },
    "gpt-5.1": {
      "id": "gpt-5.1",
      "name": "GPT-5.1",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0.13,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.1-chat-latest": {
      "id": "gpt-5.1-chat-latest",
      "name": "GPT-5.1 Chat",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0.125,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 16384
    },
    "gpt-5.1-codex": {
      "id": "gpt-5.1-codex",
      "name": "GPT-5.1 Codex",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0.125,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.1-codex-max": {
      "id": "gpt-5.1-codex-max",
      "name": "GPT-5.1 Codex Max",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0.125,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.1-codex-mini": {
      "id": "gpt-5.1-codex-mini",
      "name": "GPT-5.1 Codex mini",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 0.25,
        "output": 2,
        "cacheRead": 0.025,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.2": {
      "id": "gpt-5.2",
      "name": "GPT-5.2",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.75,
        "output": 14,
        "cacheRead": 0.175,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.2-chat-latest": {
      "id": "gpt-5.2-chat-latest",
      "name": "GPT-5.2 Chat",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.75,
        "output": 14,
        "cacheRead": 0.175,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 16384
    },
    "gpt-5.2-codex": {
      "id": "gpt-5.2-codex",
      "name": "GPT-5.2 Codex",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "cost": {
        "input": 1.75,
        "output": 14,
        "cacheRead": 0.175,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.2-pro": {
      "id": "gpt-5.2-pro",
      "name": "GPT-5.2 Pro",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 21,
        "output": 168,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.3-codex": {
      "id": "gpt-5.3-codex",
      "name": "GPT-5.3 Codex",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "cost": {
        "input": 1.75,
        "output": 14,
        "cacheRead": 0.175,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.3-codex-spark": {
      "id": "gpt-5.3-codex-spark",
      "name": "GPT-5.3 Codex Spark",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "cost": {
        "input": 1.75,
        "output": 14,
        "cacheRead": 0.175,
        "cacheWrite": 0
      },
      "contextWindow": 100000,
      "maxTokens": 32000
    },
    "o1": {
      "id": "o1",
      "name": "o1",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 15,
        "output": 60,
        "cacheRead": 7.5,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o1-mini": {
      "id": "o1-mini",
      "name": "o1-mini",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 1.1,
        "output": 4.4,
        "cacheRead": 0.55,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 65536
    },
    "o1-preview": {
      "id": "o1-preview",
      "name": "o1-preview",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 15,
        "output": 60,
        "cacheRead": 7.5,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 32768
    },
    "o1-pro": {
      "id": "o1-pro",
      "name": "o1-pro",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 150,
        "output": 600,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o3": {
      "id": "o3",
      "name": "o3",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 2,
        "output": 8,
        "cacheRead": 0.5,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o3-deep-research": {
      "id": "o3-deep-research",
      "name": "o3-deep-research",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 10,
        "output": 40,
        "cacheRead": 2.5,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o3-mini": {
      "id": "o3-mini",
      "name": "o3-mini",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 1.1,
        "output": 4.4,
        "cacheRead": 0.55,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o3-pro": {
      "id": "o3-pro",
      "name": "o3-pro",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 20,
        "output": 80,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o4-mini": {
      "id": "o4-mini",
      "name": "o4-mini",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.1,
        "output": 4.4,
        "cacheRead": 0.28,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o4-mini-deep-research": {
      "id": "o4-mini-deep-research",
      "name": "o4-mini-deep-research",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 2,
        "output": 8,
        "cacheRead": 0.5,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "text-embedding-3-large": {
      "id": "text-embedding-3-large",
      "name": "text-embedding-3-large",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0.13,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 8191,
      "maxTokens": 3072
    },
    "text-embedding-3-small": {
      "id": "text-embedding-3-small",
      "name": "text-embedding-3-small",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0.02,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 8191,
      "maxTokens": 1536
    },
    "text-embedding-ada-002": {
      "id": "text-embedding-ada-002",
      "name": "text-embedding-ada-002",
      "api": "openai-responses",
      "provider": "openai",
      "baseUrl": "https://api.openai.com/v1",
      "reasoning": false,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0.1,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 8192,
      "maxTokens": 1536
    }
  },
  "openai-codex": {
    "codex-mini-latest": {
      "id": "codex-mini-latest",
      "name": "Codex Mini",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 1.5,
        "output": 6,
        "cacheRead": 0.375,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "gpt-3.5-turbo": {
      "id": "gpt-3.5-turbo",
      "name": "GPT-3.5-turbo",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0.5,
        "output": 1.5,
        "cacheRead": 1.25,
        "cacheWrite": 0
      },
      "contextWindow": 16385,
      "maxTokens": 4096
    },
    "gpt-4": {
      "id": "gpt-4",
      "name": "GPT-4",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text"
      ],
      "cost": {
        "input": 30,
        "output": 60,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 8192,
      "maxTokens": 8192
    },
    "gpt-4-turbo": {
      "id": "gpt-4-turbo",
      "name": "GPT-4 Turbo",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 10,
        "output": 30,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 4096
    },
    "gpt-4.1": {
      "id": "gpt-4.1",
      "name": "GPT-4.1",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 2,
        "output": 8,
        "cacheRead": 0.5,
        "cacheWrite": 0
      },
      "contextWindow": 1047576,
      "maxTokens": 32768
    },
    "gpt-4.1-mini": {
      "id": "gpt-4.1-mini",
      "name": "GPT-4.1 mini",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 0.4,
        "output": 1.6,
        "cacheRead": 0.1,
        "cacheWrite": 0
      },
      "contextWindow": 1047576,
      "maxTokens": 32768
    },
    "gpt-4.1-nano": {
      "id": "gpt-4.1-nano",
      "name": "GPT-4.1 nano",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 0.1,
        "output": 0.4,
        "cacheRead": 0.03,
        "cacheWrite": 0
      },
      "contextWindow": 1047576,
      "maxTokens": 32768
    },
    "gpt-4o": {
      "id": "gpt-4o",
      "name": "GPT-4o",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 2.5,
        "output": 10,
        "cacheRead": 1.25,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 16384
    },
    "gpt-4o-2024-05-13": {
      "id": "gpt-4o-2024-05-13",
      "name": "GPT-4o (2024-05-13)",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 5,
        "output": 15,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 4096
    },
    "gpt-4o-2024-08-06": {
      "id": "gpt-4o-2024-08-06",
      "name": "GPT-4o (2024-08-06)",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 2.5,
        "output": 10,
        "cacheRead": 1.25,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 16384
    },
    "gpt-4o-2024-11-20": {
      "id": "gpt-4o-2024-11-20",
      "name": "GPT-4o (2024-11-20)",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 2.5,
        "output": 10,
        "cacheRead": 1.25,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 16384
    },
    "gpt-4o-mini": {
      "id": "gpt-4o-mini",
      "name": "GPT-4o mini",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 0.15,
        "output": 0.6,
        "cacheRead": 0.08,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 16384
    },
    "gpt-5": {
      "id": "gpt-5",
      "name": "GPT-5",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0.125,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5-chat-latest": {
      "id": "gpt-5-chat-latest",
      "name": "GPT-5 Chat (latest)",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5-codex": {
      "id": "gpt-5-codex",
      "name": "GPT-5-Codex",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0.125,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5-mini": {
      "id": "gpt-5-mini",
      "name": "GPT-5 Mini",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 0.25,
        "output": 2,
        "cacheRead": 0.025,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5-nano": {
      "id": "gpt-5-nano",
      "name": "GPT-5 Nano",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 0.05,
        "output": 0.4,
        "cacheRead": 0.005,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5-pro": {
      "id": "gpt-5-pro",
      "name": "GPT-5 Pro",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 15,
        "output": 120,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 272000
    },
    "gpt-5.1": {
      "id": "gpt-5.1",
      "name": "GPT-5.1",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0.13,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.1-chat-latest": {
      "id": "gpt-5.1-chat-latest",
      "name": "GPT-5.1 Chat",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0.125,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 16384
    },
    "gpt-5.1-codex": {
      "id": "gpt-5.1-codex",
      "name": "GPT-5.1 Codex",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0.125,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.1-codex-max": {
      "id": "gpt-5.1-codex-max",
      "name": "GPT-5.1 Codex Max",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.25,
        "output": 10,
        "cacheRead": 0.125,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.1-codex-mini": {
      "id": "gpt-5.1-codex-mini",
      "name": "GPT-5.1 Codex mini",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 0.25,
        "output": 2,
        "cacheRead": 0.025,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.2": {
      "id": "gpt-5.2",
      "name": "GPT-5.2",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.75,
        "output": 14,
        "cacheRead": 0.175,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.2-chat-latest": {
      "id": "gpt-5.2-chat-latest",
      "name": "GPT-5.2 Chat",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.75,
        "output": 14,
        "cacheRead": 0.175,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 16384
    },
    "gpt-5.2-codex": {
      "id": "gpt-5.2-codex",
      "name": "GPT-5.2 Codex",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "cost": {
        "input": 1.75,
        "output": 14,
        "cacheRead": 0.175,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.2-pro": {
      "id": "gpt-5.2-pro",
      "name": "GPT-5.2 Pro",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 21,
        "output": 168,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.3-codex": {
      "id": "gpt-5.3-codex",
      "name": "GPT-5.3 Codex",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "cost": {
        "input": 1.75,
        "output": 14,
        "cacheRead": 0.175,
        "cacheWrite": 0
      },
      "contextWindow": 272000,
      "maxTokens": 128000
    },
    "gpt-5.3-codex-spark": {
      "id": "gpt-5.3-codex-spark",
      "name": "GPT-5.3 Codex Spark",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image",
        "pdf"
      ],
      "cost": {
        "input": 1.75,
        "output": 14,
        "cacheRead": 0.175,
        "cacheWrite": 0
      },
      "contextWindow": 100000,
      "maxTokens": 32000
    },
    "o1": {
      "id": "o1",
      "name": "o1",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 15,
        "output": 60,
        "cacheRead": 7.5,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o1-mini": {
      "id": "o1-mini",
      "name": "o1-mini",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 1.1,
        "output": 4.4,
        "cacheRead": 0.55,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 65536
    },
    "o1-preview": {
      "id": "o1-preview",
      "name": "o1-preview",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 15,
        "output": 60,
        "cacheRead": 7.5,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 32768
    },
    "o1-pro": {
      "id": "o1-pro",
      "name": "o1-pro",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 150,
        "output": 600,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o3": {
      "id": "o3",
      "name": "o3",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 2,
        "output": 8,
        "cacheRead": 0.5,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o3-deep-research": {
      "id": "o3-deep-research",
      "name": "o3-deep-research",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 10,
        "output": 40,
        "cacheRead": 2.5,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o3-mini": {
      "id": "o3-mini",
      "name": "o3-mini",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 1.1,
        "output": 4.4,
        "cacheRead": 0.55,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o3-pro": {
      "id": "o3-pro",
      "name": "o3-pro",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 20,
        "output": 80,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o4-mini": {
      "id": "o4-mini",
      "name": "o4-mini",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 1.1,
        "output": 4.4,
        "cacheRead": 0.28,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "o4-mini-deep-research": {
      "id": "o4-mini-deep-research",
      "name": "o4-mini-deep-research",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": true,
      "input": [
        "text",
        "image"
      ],
      "cost": {
        "input": 2,
        "output": 8,
        "cacheRead": 0.5,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 100000
    },
    "text-embedding-3-large": {
      "id": "text-embedding-3-large",
      "name": "text-embedding-3-large",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0.13,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 8191,
      "maxTokens": 3072
    },
    "text-embedding-3-small": {
      "id": "text-embedding-3-small",
      "name": "text-embedding-3-small",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0.02,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 8191,
      "maxTokens": 1536
    },
    "text-embedding-ada-002": {
      "id": "text-embedding-ada-002",
      "name": "text-embedding-ada-002",
      "api": "openai-codex-responses",
      "provider": "openai-codex",
      "baseUrl": "https://chatgpt.com/backend-api",
      "reasoning": false,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0.1,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 8192,
      "maxTokens": 1536
    }
  },
  "zai": {
    "glm-4.5": {
      "id": "glm-4.5",
      "name": "GLM-4.5",
      "api": "openai-completions",
      "provider": "zai",
      "baseUrl": "https://api.z.ai/api/coding/paas/v4",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 131072,
      "maxTokens": 98304,
      "compat": {
        "supportsDeveloperRole": false,
        "thinkingFormat": "zai"
      }
    },
    "glm-4.5-air": {
      "id": "glm-4.5-air",
      "name": "GLM-4.5-Air",
      "api": "openai-completions",
      "provider": "zai",
      "baseUrl": "https://api.z.ai/api/coding/paas/v4",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 131072,
      "maxTokens": 98304,
      "compat": {
        "supportsDeveloperRole": false,
        "thinkingFormat": "zai"
      }
    },
    "glm-4.5-flash": {
      "id": "glm-4.5-flash",
      "name": "GLM-4.5-Flash",
      "api": "openai-completions",
      "provider": "zai",
      "baseUrl": "https://api.z.ai/api/coding/paas/v4",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 131072,
      "maxTokens": 98304,
      "compat": {
        "supportsDeveloperRole": false,
        "thinkingFormat": "zai"
      }
    },
    "glm-4.5v": {
      "id": "glm-4.5v",
      "name": "GLM-4.5V",
      "api": "openai-completions",
      "provider": "zai",
      "baseUrl": "https://api.z.ai/api/coding/paas/v4",
      "reasoning": true,
      "input": [
        "text",
        "image",
        "video"
      ],
      "cost": {
        "input": 0,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 64000,
      "maxTokens": 16384,
      "compat": {
        "supportsDeveloperRole": false,
        "thinkingFormat": "zai"
      }
    },
    "glm-4.6": {
      "id": "glm-4.6",
      "name": "GLM-4.6",
      "api": "openai-completions",
      "provider": "zai",
      "baseUrl": "https://api.z.ai/api/coding/paas/v4",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 204800,
      "maxTokens": 131072,
      "compat": {
        "supportsDeveloperRole": false,
        "thinkingFormat": "zai"
      }
    },
    "glm-4.6v": {
      "id": "glm-4.6v",
      "name": "GLM-4.6V",
      "api": "openai-completions",
      "provider": "zai",
      "baseUrl": "https://api.z.ai/api/coding/paas/v4",
      "reasoning": true,
      "input": [
        "text",
        "image",
        "video"
      ],
      "cost": {
        "input": 0,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 128000,
      "maxTokens": 32768,
      "compat": {
        "supportsDeveloperRole": false,
        "thinkingFormat": "zai"
      }
    },
    "glm-4.7": {
      "id": "glm-4.7",
      "name": "GLM-4.7",
      "api": "openai-completions",
      "provider": "zai",
      "baseUrl": "https://api.z.ai/api/coding/paas/v4",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 204800,
      "maxTokens": 131072,
      "compat": {
        "supportsDeveloperRole": false,
        "thinkingFormat": "zai"
      }
    },
    "glm-4.7-flash": {
      "id": "glm-4.7-flash",
      "name": "GLM-4.7-Flash",
      "api": "openai-completions",
      "provider": "zai",
      "baseUrl": "https://api.z.ai/api/coding/paas/v4",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 131072,
      "compat": {
        "supportsDeveloperRole": false,
        "thinkingFormat": "zai"
      }
    },
    "glm-4.7-flashx": {
      "id": "glm-4.7-flashx",
      "name": "GLM-4.7-FlashX",
      "api": "openai-completions",
      "provider": "zai",
      "baseUrl": "https://api.z.ai/api/coding/paas/v4",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0.07,
        "output": 0.4,
        "cacheRead": 0.01,
        "cacheWrite": 0
      },
      "contextWindow": 200000,
      "maxTokens": 131072,
      "compat": {
        "supportsDeveloperRole": false,
        "thinkingFormat": "zai"
      }
    },
    "glm-5": {
      "id": "glm-5",
      "name": "GLM-5",
      "api": "openai-completions",
      "provider": "zai",
      "baseUrl": "https://api.z.ai/api/coding/paas/v4",
      "reasoning": true,
      "input": [
        "text"
      ],
      "cost": {
        "input": 0,
        "output": 0,
        "cacheRead": 0,
        "cacheWrite": 0
      },
      "contextWindow": 204800,
      "maxTokens": 131072,
      "compat": {
        "supportsDeveloperRole": false,
        "thinkingFormat": "zai"
      }
    }
  }
}
`
