package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/bstncartwright/gopher/pkg/ai"
)

const (
	defaultModelsDevURL = "https://models.dev/api.json"
)

var generatedFileTemplate = template.Must(template.New("models_generated").Parse(`package ai

//go:generate go run ../../cmd/modelcataloggen -out models_generated.go
// Code generated by go run ./cmd/modelcataloggen. DO NOT EDIT.
// Source: {{.SourceURL}}
// Provider scope in this port: {{.ProviderScope}}.
var generatedModelsJSON = ` + "`" + `
{{.JSON}}
` + "`" + `
`))

type generatorConfig struct {
	OutPath    string
	SourceURL  string
	HTTPClient *http.Client
}

type generatedFileData struct {
	SourceURL     string
	ProviderScope string
	JSON          string
}

type modelsDevProvider struct {
	ID     string                    `json:"id"`
	API    string                    `json:"api"`
	Name   string                    `json:"name"`
	Doc    string                    `json:"doc"`
	Models map[string]modelsDevModel `json:"models"`
}

type modelsDevModel struct {
	ID         string              `json:"id"`
	Name       string              `json:"name"`
	Family     string              `json:"family"`
	Reasoning  bool                `json:"reasoning"`
	Modalities modelsDevModalities `json:"modalities"`
	Cost       modelsDevCost       `json:"cost"`
	Limit      modelsDevLimit      `json:"limit"`
}

type modelsDevModalities struct {
	Input  []string `json:"input"`
	Output []string `json:"output"`
}

type modelsDevCost struct {
	Input      float64 `json:"input"`
	Output     float64 `json:"output"`
	CacheRead  float64 `json:"cache_read"`
	CacheWrite float64 `json:"cache_write"`
}

type modelsDevLimit struct {
	Context int `json:"context"`
	Input   int `json:"input"`
	Output  int `json:"output"`
}

func main() {
	cfg := generatorConfig{}
	flag.StringVar(&cfg.OutPath, "out", filepath.Join("pkg", "ai", "models_generated.go"), "output path for generated Go source")
	flag.StringVar(&cfg.SourceURL, "source", defaultModelsDevURL, "machine-readable models.dev catalog URL")
	flag.Parse()

	cfg.HTTPClient = &http.Client{Timeout: 60 * time.Second}
	if err := run(cfg); err != nil {
		fmt.Fprintf(os.Stderr, "modelcataloggen: %v\n", err)
		os.Exit(1)
	}
}

func run(cfg generatorConfig) error {
	if strings.TrimSpace(cfg.OutPath) == "" {
		return fmt.Errorf("output path is required")
	}
	if strings.TrimSpace(cfg.SourceURL) == "" {
		return fmt.Errorf("source URL is required")
	}
	if cfg.HTTPClient == nil {
		cfg.HTTPClient = http.DefaultClient
	}

	providers, err := fetchModelsDevProviders(cfg.HTTPClient, cfg.SourceURL)
	if err != nil {
		return err
	}
	filtered := buildGopherCatalog(providers)
	if len(filtered) == 0 {
		return fmt.Errorf("no supported models found in %s", cfg.SourceURL)
	}

	encodedJSON, err := json.MarshalIndent(filtered, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal filtered models: %w", err)
	}

	var rendered strings.Builder
	if err := generatedFileTemplate.Execute(&rendered, generatedFileData{
		SourceURL:     strings.TrimSpace(cfg.SourceURL),
		ProviderScope: strings.Join(providerNames(filtered), ", "),
		JSON:          string(encodedJSON),
	}); err != nil {
		return fmt.Errorf("render generated file: %w", err)
	}

	formatted, err := format.Source([]byte(rendered.String()))
	if err != nil {
		return fmt.Errorf("gofmt generated file: %w", err)
	}
	if err := os.WriteFile(cfg.OutPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write generated file %s: %w", cfg.OutPath, err)
	}
	return nil
}

func fetchModelsDevProviders(client *http.Client, sourceURL string) (map[string]modelsDevProvider, error) {
	req, err := http.NewRequest(http.MethodGet, sourceURL, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", "gopher-modelcataloggen/1.0")
	req.Header.Set("Accept", "application/json")

	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 2048))
		return nil, fmt.Errorf("GET %s: status %s: %s", sourceURL, resp.Status, strings.TrimSpace(string(body)))
	}

	var providers map[string]modelsDevProvider
	if err := json.NewDecoder(resp.Body).Decode(&providers); err != nil {
		return nil, fmt.Errorf("decode models.dev payload: %w", err)
	}
	return providers, nil
}

func buildGopherCatalog(source map[string]modelsDevProvider) map[string]map[string]ai.Model {
	out := map[string]map[string]ai.Model{}

	addProviderModels(out, "openai", source["openai"], transformModelsDevProvider("openai", source["openai"], ai.APIOpenAIResponses, "https://api.openai.com/v1", nil))
	addProviderModels(out, "openai-codex", source["openai"], transformOpenAICodexModels(source["openai"]))
	addProviderModels(out, "kimi-coding", source["kimi-for-coding"], transformModelsDevProvider("kimi-coding", source["kimi-for-coding"], ai.APIAnthropicMessages, source["kimi-for-coding"].API, nil))
	addProviderModels(out, "zai", source["zai-coding-plan"], transformModelsDevProvider("zai", source["zai-coding-plan"], ai.APIOpenAICompletions, source["zai-coding-plan"].API, zaiCompat()))

	return out
}

func transformOpenAICodexModels(provider modelsDevProvider) map[string]ai.Model {
	out := map[string]ai.Model{}
	for modelID, model := range provider.Models {
		out[modelID] = toAIModel("openai-codex", model, ai.APIOpenAICodexResponse, "https://chatgpt.com/backend-api", nil)
	}
	return out
}

func transformModelsDevProvider(targetProvider string, provider modelsDevProvider, apiType ai.API, baseURL string, compat *ai.OpenAICompletionsCompat) map[string]ai.Model {
	out := map[string]ai.Model{}
	for modelID, model := range provider.Models {
		out[modelID] = toAIModel(targetProvider, model, apiType, baseURL, compat)
	}
	return out
}

func toAIModel(targetProvider string, model modelsDevModel, apiType ai.API, baseURL string, compat *ai.OpenAICompletionsCompat) ai.Model {
	contextWindow := model.Limit.Input
	if contextWindow <= 0 {
		contextWindow = model.Limit.Context
	}
	var responsesCompat *ai.OpenAIResponsesCompat
	if apiType == ai.APIOpenAIResponses || apiType == ai.APIOpenAICodexResponse {
		responsesCompat = &ai.OpenAIResponsesCompat{
			SupportsHostedWebSearch: boolPtr(targetProvider == "openai" || targetProvider == "openai-codex"),
		}
	}
	return ai.Model{
		ID:        strings.TrimSpace(model.ID),
		Name:      strings.TrimSpace(model.Name),
		API:       apiType,
		Provider:  ai.Provider(targetProvider),
		BaseURL:   strings.TrimSpace(baseURL),
		Reasoning: model.Reasoning,
		Input:     append([]string(nil), model.Modalities.Input...),
		Cost: ai.ModelCost{
			Input:      model.Cost.Input,
			Output:     model.Cost.Output,
			CacheRead:  model.Cost.CacheRead,
			CacheWrite: model.Cost.CacheWrite,
		},
		ContextWindow:   contextWindow,
		MaxTokens:       model.Limit.Output,
		Compat:          cloneCompat(compat),
		ResponsesCompat: responsesCompat,
	}
}

func zaiCompat() *ai.OpenAICompletionsCompat {
	return &ai.OpenAICompletionsCompat{
		SupportsDeveloperRole: boolPtr(false),
		ThinkingFormat:        "zai",
	}
}

func cloneCompat(in *ai.OpenAICompletionsCompat) *ai.OpenAICompletionsCompat {
	if in == nil {
		return nil
	}
	out := *in
	return &out
}

func addProviderModels(out map[string]map[string]ai.Model, provider string, source modelsDevProvider, models map[string]ai.Model) {
	if strings.TrimSpace(source.ID) == "" || len(models) == 0 {
		return
	}
	out[provider] = models
}

func providerNames(models map[string]map[string]ai.Model) []string {
	out := make([]string, 0, len(models))
	for provider := range models {
		out = append(out, provider)
	}
	sort.Strings(out)
	return out
}

func boolPtr(v bool) *bool {
	return &v
}
