name: pr-tests

on:
  pull_request:
    branches:
      - main
  merge_group:

permissions:
  contents: read

env:
  GO_VERSION: "1.26.1"

jobs:
  lint-gofmt:
    name: lint-gofmt
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: verify gofmt
        run: |
          files="$(gofmt -l .)"
          if [ -n "$files" ]; then
            echo "these files are not gofmt-formatted:"
            echo "$files"
            exit 1
          fi

  lint-vet:
    name: lint-go-vet
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.1"

      - name: setup bun
        uses: oven-sh/setup-bun@v2

      - name: build frontend
        run: bun install && bun run build
        working-directory: frontend/admin

      - name: build
        run: go build ./...

      - name: run tests
        run: go test ./...
